services:
  moocleancode:
    image: moo-image
    build:
      context: .
      dockerfile: MooCleanCode/Dockerfile
    depends_on:
      - mongodb
    environment:
      - MONGO-CONNECTION_STRING=mongodb://mongodb:27017/moogamedatabase
    stdin_open: true
    tty: true
  
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
